/**
 * Vendors the handful of design tokens stage 1 needs into `src/collector/tokens.gen.ts`.
 *
 * The pill renders inside a shadow root on someone else's page. Custom properties still
 * inherit from the host document, so a Dash0-styled host resolves the real tokens; a
 * customer app resolves nothing. Every generated value is therefore
 * `var(--token, <resolved literal>)` — the codebase's token when it exists, the design
 * system's own value when it does not. We never emit a bare hex.
 *
 * Only the dark-default scope is read (`:root`, `.dark`). d0bar's panel is dark by design,
 * regardless of the host's theme.
 *
 * Fails the build if any requested token cannot be resolved to a literal.
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokenDir = join(root, "design_handoff_d0bar", "tokens");
const out = join(root, "src", "collector", "tokens.gen.ts");

/** Tokens stage 1 references, keyed by the identifier the pill uses. */
const WANTED = {
  bg: "--lvl-1-bg",
  stroke: "--lvl-1-stroke",
  hoverBg: "--lvl-1-hover-bg",
  hoverStroke: "--lvl-1-hover-stroke",
  badgeBg: "--lvl-2-bg",
  textIntense: "--lvl-0-intense-text",
  text: "--lvl-0-text",
  textSubtle: "--lvl-subtle-text",
  cta: "--cta-bg",
  healthy: "--healthy-bg",
  warning: "--warning-bg",
  warningInline: "--warning-text-inline",
  error: "--error-bg",
  shadow: "--shadow-lg",
  fontSans: "--font-sans",
  fontMono: "--font-mono",
  /* Panel-only from here. Stage 1 references none of these, and the prelude is shared, so
     an unused alias costs a few bytes of CSS text rather than anything at runtime. */
  lvl2Bg: "--lvl-2-bg",
  lvl2Stroke: "--lvl-2-stroke",
  lvl3Bg: "--lvl-3-bg",
  shadowXl: "--shadow-xl",
  shadow2xl: "--shadow-2xl",
};

const DARK_SCOPE = /^(:root|\.dark)(\s*,\s*(:root|\.dark))*$/;

/** Top-level `selector { body }` blocks only; nested at-rules are skipped wholesale. */
function* topLevelBlocks(css) {
  let i = 0;
  while (i < css.length) {
    const open = css.indexOf("{", i);
    if (open === -1) return;
    let depth = 1;
    let j = open + 1;
    while (j < css.length && depth > 0) {
      if (css[j] === "{") depth++;
      else if (css[j] === "}") depth--;
      j++;
    }
    const selector = css
      .slice(i, open)
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .trim();
    yield { selector, body: css.slice(open + 1, j - 1) };
    i = j;
  }
}

function collect() {
  const declarations = new Map();
  const files = readdirSync(tokenDir)
    .filter((f) => f.endsWith(".css"))
    .sort();
  for (const file of files) {
    const css = readFileSync(join(tokenDir, file), "utf8");
    for (const { selector, body } of topLevelBlocks(css)) {
      if (!DARK_SCOPE.test(selector)) continue;
      for (const m of body.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/gi)) {
        declarations.set(m[1], m[2].trim());
      }
    }
  }
  return declarations;
}

/** Follows `var(--a)` chains to a literal. Honours an inline fallback if the chain dead-ends. */
function resolve(name, declarations, seen = new Set()) {
  if (seen.has(name)) throw new Error(`token cycle at ${name}`);
  seen.add(name);
  const raw = declarations.get(name);
  if (raw === undefined) return undefined;
  const single = raw.match(/^var\(\s*(--[a-z0-9-]+)\s*(?:,\s*([\s\S]+))?\)$/i);
  if (!single) return raw;
  const next = resolve(single[1], declarations, seen);
  return next ?? single[2]?.trim();
}

const declarations = collect();
const missing = [];
const resolved = {};
for (const [key, token] of Object.entries(WANTED)) {
  const literal = resolve(token, declarations);
  if (!literal) missing.push(token);
  else resolved[key] = { token, literal };
}

if (missing.length) {
  console.error(`vendor-tokens: unresolved token(s): ${missing.join(", ")}`);
  process.exit(1);
}

/* Kebab-case alias per token: `--lvl-1-hover-bg` is referenced as `--d0-hover-bg`.
   The indirection is declared once on :host and referenced everywhere else, which keeps the
   stylesheet short and gzip-friendly — a long `var(--token, #literal)` pair repeated at
   every use site is the single largest thing in the stage-1 bundle otherwise. */
const alias = (key) => `--d0-${key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}`;

const prelude =
  ":host{" +
  Object.entries(resolved)
    .map(([key, { token, literal }]) => `${alias(key)}:var(${token}, ${literal})`)
    .join(";") +
  "}";

const aliases = Object.keys(resolved)
  .map((key) => `  ${key}: "var(${alias(key)})",`)
  .join("\n");

writeFileSync(
  out,
  `/* Generated by scripts/vendor-tokens.mjs — do not edit.

   PRELUDE declares one d0bar-local alias per design token, each preferring the host's own
   Dash0 token and falling back to the design system's resolved value — so the pill is
   correct on a page that has neither. V references those aliases from TypeScript. */

export const PRELUDE = ${JSON.stringify(prelude)};

export const V = {
${aliases}
} as const;
`,
  "utf8",
);

console.log(`vendor-tokens: resolved ${Object.keys(resolved).length} tokens → ${out}`);
